/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "./src/lib/server/db/schema";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    activities: {
      name: "activities",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "userId"
          >,
          serverName: "user_id",
        },
        leadId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "leadId"
          >,
          serverName: "lead_id",
        },
        dealId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "dealId"
          >,
          serverName: "deal_id",
        },
        type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "type"
          >,
        },
        subject: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "subject"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "description"
          >,
        },
        outcome: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "outcome"
          >,
        },
        duration: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "duration"
          >,
        },
        scheduledAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "scheduledAt"
          >,
          serverName: "scheduled_at",
        },
        completedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "completedAt"
          >,
          serverName: "completed_at",
        },
        isCompleted: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "isCompleted"
          >,
          serverName: "is_completed",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "activities",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    aiInsights: {
      name: "aiInsights",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "userId"
          >,
          serverName: "user_id",
        },
        leadId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "leadId"
          >,
          serverName: "lead_id",
        },
        dealId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "dealId"
          >,
          serverName: "deal_id",
        },
        type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "type"
          >,
        },
        category: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "category"
          >,
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "title"
          >,
        },
        description: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "description"
          >,
        },
        recommendation: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "recommendation"
          >,
        },
        confidence: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "confidence"
          >,
        },
        impact: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "impact"
          >,
        },
        actionTaken: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "actionTaken"
          >,
          serverName: "action_taken",
        },
        actionTakenAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "actionTakenAt"
          >,
          serverName: "action_taken_at",
        },
        dismissedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "dismissedAt"
          >,
          serverName: "dismissed_at",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "aiInsights",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "ai_insights",
    },
    apiKeys: {
      name: "apiKeys",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "userId"
          >,
          serverName: "user_id",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "name"
          >,
        },
        keyHash: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "keyHash"
          >,
          serverName: "key_hash",
        },
        permissions: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "permissions"
          >,
        },
        lastUsedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "lastUsedAt"
          >,
          serverName: "last_used_at",
        },
        expiresAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "expiresAt"
          >,
          serverName: "expires_at",
        },
        isActive: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "isActive"
          >,
          serverName: "is_active",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "apiKeys",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "api_keys",
    },
    auditLogs: {
      name: "auditLogs",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "userId"
          >,
          serverName: "user_id",
        },
        action: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "action"
          >,
        },
        resource: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "resource"
          >,
        },
        resourceId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "resourceId"
          >,
          serverName: "resource_id",
        },
        oldValues: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "oldValues"
          >,
          serverName: "old_values",
        },
        newValues: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "newValues"
          >,
          serverName: "new_values",
        },
        ipAddress: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "ipAddress"
          >,
          serverName: "ip_address",
        },
        userAgent: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "userAgent"
          >,
          serverName: "user_agent",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "auditLogs",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "audit_logs",
    },
    deals: {
      name: "deals",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        leadId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "leadId"
          >,
          serverName: "lead_id",
        },
        assignedTo: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "assignedTo"
          >,
          serverName: "assigned_to",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "name"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "description"
          >,
        },
        value: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "value"
          >,
        },
        currency: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "currency"
          >,
        },
        stage: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "stage"
          >,
        },
        probability: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "probability"
          >,
        },
        expectedCloseDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "expectedCloseDate"
          >,
          serverName: "expected_close_date",
        },
        actualCloseDate: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "actualCloseDate"
          >,
          serverName: "actual_close_date",
        },
        lostReason: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "lostReason"
          >,
          serverName: "lost_reason",
        },
        competitorInfo: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "competitorInfo"
          >,
          serverName: "competitor_info",
        },
        tags: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "tags"
          >,
        },
        customFields: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "customFields"
          >,
          serverName: "custom_fields",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "deals",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    emailTemplates: {
      name: "emailTemplates",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        createdBy: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "createdBy"
          >,
          serverName: "created_by",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "name"
          >,
        },
        subject: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "subject"
          >,
        },
        content: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "content"
          >,
        },
        type: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "type"
          >,
        },
        variables: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "variables"
          >,
        },
        isActive: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "isActive"
          >,
          serverName: "is_active",
        },
        usageCount: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "usageCount"
          >,
          serverName: "usage_count",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "emailTemplates",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "email_templates",
    },
    integrations: {
      name: "integrations",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "name"
          >,
        },
        type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "type"
          >,
        },
        provider: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "provider"
          >,
        },
        status: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "status"
          >,
        },
        config: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "config"
          >,
        },
        credentials: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "credentials"
          >,
        },
        lastSyncAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "lastSyncAt"
          >,
          serverName: "last_sync_at",
        },
        syncStatus: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "syncStatus"
          >,
          serverName: "sync_status",
        },
        errorMessage: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "errorMessage"
          >,
          serverName: "error_message",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "integrations",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    leads: {
      name: "leads",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        assignedTo: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "assignedTo"
          >,
          serverName: "assigned_to",
        },
        firstName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "firstName"
          >,
          serverName: "first_name",
        },
        lastName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "lastName"
          >,
          serverName: "last_name",
        },
        email: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "email"
          >,
        },
        phone: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "phone"
          >,
        },
        company: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "company"
          >,
        },
        title: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "title"
          >,
        },
        industry: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "industry"
          >,
        },
        website: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "website"
          >,
        },
        linkedinUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "linkedinUrl"
          >,
          serverName: "linkedin_url",
        },
        address: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "address"
          >,
        },
        city: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "city"
          >,
        },
        state: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "state"
          >,
        },
        country: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "country"
          >,
        },
        zipCode: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "zipCode"
          >,
          serverName: "zip_code",
        },
        source: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "source"
          >,
        },
        status: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "status"
          >,
        },
        leadScore: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "leadScore"
          >,
          serverName: "lead_score",
        },
        estimatedValue: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "estimatedValue"
          >,
          serverName: "estimated_value",
        },
        probability: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "probability"
          >,
        },
        tags: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "tags"
          >,
        },
        notes: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "notes"
          >,
        },
        customFields: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "customFields"
          >,
          serverName: "custom_fields",
        },
        lastContactedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "lastContactedAt"
          >,
          serverName: "last_contacted_at",
        },
        qualifiedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "qualifiedAt"
          >,
          serverName: "qualified_at",
        },
        convertedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "convertedAt"
          >,
          serverName: "converted_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "leads",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    notifications: {
      name: "notifications",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "userId"
          >,
          serverName: "user_id",
        },
        type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "type"
          >,
        },
        title: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "title"
          >,
        },
        message: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "message"
          >,
        },
        actionUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "actionUrl"
          >,
          serverName: "action_url",
        },
        isRead: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "isRead"
          >,
          serverName: "is_read",
        },
        readAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "readAt"
          >,
          serverName: "read_at",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notifications",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
    },
    organizationMembers: {
      name: "organizationMembers",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "userId"
          >,
          serverName: "user_id",
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "role"
          >,
        },
        permissions: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "permissions"
          >,
        },
        invitedBy: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "invitedBy"
          >,
          serverName: "invited_by",
        },
        invitedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "invitedAt"
          >,
          serverName: "invited_at",
        },
        joinedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "joinedAt"
          >,
          serverName: "joined_at",
        },
        isActive: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "isActive"
          >,
          serverName: "is_active",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizationMembers",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "organization_members",
    },
    organizations: {
      name: "organizations",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "name"
          >,
        },
        slug: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "slug"
          >,
        },
        domain: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "domain"
          >,
        },
        logo: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "logo"
          >,
        },
        industry: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "industry"
          >,
        },
        size: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "size"
          >,
        },
        website: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "website"
          >,
        },
        address: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "address"
          >,
        },
        city: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "city"
          >,
        },
        state: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "state"
          >,
        },
        country: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "country"
          >,
        },
        zipCode: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "zipCode"
          >,
          serverName: "zip_code",
        },
        phone: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "phone"
          >,
        },
        settings: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "settings"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "organizations",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    payments: {
      name: "payments",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        subscriptionId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "subscriptionId"
          >,
          serverName: "subscription_id",
        },
        stripePaymentIntentId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "stripePaymentIntentId"
          >,
          serverName: "stripe_payment_intent_id",
        },
        stripeInvoiceId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "stripeInvoiceId"
          >,
          serverName: "stripe_invoice_id",
        },
        amount: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "amount"
          >,
        },
        currency: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "currency"
          >,
        },
        status: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "status"
          >,
        },
        paymentMethod: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "paymentMethod"
          >,
          serverName: "payment_method",
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "description"
          >,
        },
        receiptUrl: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "receiptUrl"
          >,
          serverName: "receipt_url",
        },
        failureReason: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "failureReason"
          >,
          serverName: "failure_reason",
        },
        refundedAmount: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "refundedAmount"
          >,
          serverName: "refunded_amount",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "metadata"
          >,
        },
        paidAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "paidAt"
          >,
          serverName: "paid_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "payments",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    subscriptionPlans: {
      name: "subscriptionPlans",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "name"
          >,
        },
        slug: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "slug"
          >,
        },
        description: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "description"
          >,
        },
        price: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "price"
          >,
        },
        currency: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "currency"
          >,
        },
        interval: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "interval"
          >,
        },
        intervalCount: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "intervalCount"
          >,
          serverName: "interval_count",
        },
        trialDays: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "trialDays"
          >,
          serverName: "trial_days",
        },
        features: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "features"
          >,
        },
        limits: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "limits"
          >,
        },
        isActive: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "isActive"
          >,
          serverName: "is_active",
        },
        sortOrder: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "sortOrder"
          >,
          serverName: "sort_order",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptionPlans",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "subscription_plans",
    },
    subscriptions: {
      name: "subscriptions",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        planId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "planId"
          >,
          serverName: "plan_id",
        },
        stripeSubscriptionId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "stripeSubscriptionId"
          >,
          serverName: "stripe_subscription_id",
        },
        stripeCustomerId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "stripeCustomerId"
          >,
          serverName: "stripe_customer_id",
        },
        status: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "status"
          >,
        },
        currentPeriodStart: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "currentPeriodStart"
          >,
          serverName: "current_period_start",
        },
        currentPeriodEnd: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "currentPeriodEnd"
          >,
          serverName: "current_period_end",
        },
        trialStart: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "trialStart"
          >,
          serverName: "trial_start",
        },
        trialEnd: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "trialEnd"
          >,
          serverName: "trial_end",
        },
        canceledAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "canceledAt"
          >,
          serverName: "canceled_at",
        },
        cancelAtPeriodEnd: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "cancelAtPeriodEnd"
          >,
          serverName: "cancel_at_period_end",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "metadata"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "subscriptions",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    usageAnalytics: {
      name: "usageAnalytics",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "userId"
          >,
          serverName: "user_id",
        },
        feature: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "feature"
          >,
        },
        action: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "action"
          >,
        },
        count: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "count"
          >,
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "metadata"
          >,
        },
        date: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "date"
          >,
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usageAnalytics",
            "createdAt"
          >,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "usage_analytics",
    },
    users: {
      name: "users",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "id"
          >,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "email"
          >,
        },
        firstName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "firstName"
          >,
          serverName: "first_name",
        },
        lastName: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "lastName"
          >,
          serverName: "last_name",
        },
        avatar: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "avatar"
          >,
        },
        title: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "title"
          >,
        },
        department: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "department"
          >,
        },
        phone: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "phone"
          >,
        },
        timezone: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "timezone"
          >,
        },
        language: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "language"
          >,
        },
        bio: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "bio"
          >,
        },
        isActive: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "isActive"
          >,
          serverName: "is_active",
        },
        lastLoginAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "lastLoginAt"
          >,
          serverName: "last_login_at",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "users",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
    webhooks: {
      name: "webhooks",
      columns: {
        id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "id"
          >,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "organizationId"
          >,
          serverName: "organization_id",
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "name"
          >,
        },
        url: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "url"
          >,
        },
        events: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "events"
          >,
        },
        secret: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "secret"
          >,
        },
        isActive: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "isActive"
          >,
          serverName: "is_active",
        },
        lastTriggeredAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "lastTriggeredAt"
          >,
          serverName: "last_triggered_at",
        },
        failureCount: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "failureCount"
          >,
          serverName: "failure_count",
        },
        createdAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "createdAt"
          >,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "webhooks",
            "updatedAt"
          >,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
    },
  },
  relationships: {},
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
